apiVersion: v2
name: external-secrets-operator
description: Umbrella chart for external-secrets-operator deployment
type: application
version: 1.1.0
dependencies:
  - name: external-secrets
    version: 1.0.0
    repository: https://charts.external-secrets.io
