apiVersion: v2
name: external-secrets-operator
description: Umbrella chart for external-secrets-operator deployment
type: application
version: 0.2.0
dependencies:
  - name: external-secrets
    version: 1.3.1
    repository: https://charts.external-secrets.io
