apiVersion: v2
name: external-dns
description: Umbrella chart for external-dns deployment
type: application
version: 0.2.0
dependencies:
  - name: external-dns
    version: 1.20.0
    repository: https://kubernetes-sigs.github.io/external-dns/
