apiVersion: v2
name: democratic-csi-iscsi
description: Umbrella chart for democratic-csi deployment
type: application
version: 0.2.0
dependencies:
  - name: democratic-csi
    version: 0.15.1
    repository: https://democratic-csi.github.io/charts/
