apiVersion: v2
name: certmanager
description: Umbrella chart for certmanager deployment
type: application
version: 0.2.0
dependencies:
  - name: cert-manager
    version: v1.19.2
    repository: https://charts.jetstack.io
