metrics:
  enabled: false

ha:
  # -- Enable high availability
  enabled: true
  # -- Number of replicas
  replicas: 2

webhook:
  cert:
    certManager:
      enabled: true
      issuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: ca-issuer

certController:
  # -- Specifies whether the cert-controller should be created.
  enabled: false

logLevel: info

crds:
  enabled: true