apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-postgresql-secret
  namespace: "{{ .Release.Namespace }}"
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mealie-postgresql-secret
    creationPolicy: Owner
  data:
    - secretKey: database_name
      remoteRef:
        key: apps/mealie/postgres
        property: database_name
    - secretKey: database_username
      remoteRef:
        key: apps/mealie/postgres
        property: database_username
    - secretKey: database_password
      remoteRef:
        key: apps/mealie/postgres
        property: database_password
    - secretKey: superuser_password
      remoteRef:
        key: apps/mealie/postgres
        property: superuser_password
    - secretKey: superuser_username
      remoteRef:
        key: apps/mealie/postgres
        property: superuser_username