apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-oidc-client-secret
  namespace: "{{ .Release.Namespace }}"
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mealie-oidc-client-secret
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: apps/mealie/oidc
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: apps/mealie/oidc
        property: client_secret
    - secretKey: configuration_url
      remoteRef:
        key: apps/mealie/oidc
        property: configuration_url
    - secretKey: admin_group
      remoteRef:
        key: apps/mealie/oidc
        property: client_secret
    - secretKey: user_group
      remoteRef:
        key: apps/mealie/oidc
        property: user_group