apiVersion: v2
name: metallb
description: Umbrella chart for metallb deployment
type: application
version: 0.2.0
dependencies:
  - name: metallb
    version: 0.15.3
    repository: https://metallb.github.io/metallb/
