apiVersion: v2
name: mealie
description: Umbrella chart for external-dns deployment
type: application
version: 1.0.0
dependencies:
  - name: app-template
    alias: mealie
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 4.4.0
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.0.0