apiVersion: v2
name: mealie
description: Umbrella chart for external-dns deployment
type: application
version: 0.2.1
dependencies:
  - name: app-template
    alias: mealie
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 4.6.2
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.7.27
